import { Field } from "./formSchema";

export interface FormScheme {
  form_label: string;
  fields: Field[];
}

export const fieldsJson: FormScheme[] = [
  {
    form_label: "Fuel Voucher",
    fields: [
      {
        field: "autocomplete",
        field_id: "supplier",
        field_label: "Supplier",
        field_mandatory: "true",
        field_placeholder: "e.g Shell",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select supplier",
        field_options: [
          {
            value: "Valero",
          },
          {
            value: "Citgo",
          },
          {
            value: "Marathon",
          },
          {
            value: "Shell",
          },
        ],
        field_layout: "vertical",
      },
      {
        field: "autocomplete",
        field_id: "ship_terminal",
        field_label: "Ship from terminal",
        field_mandatory: "true",
        field_placeholder: "e.g Motiva Enterprise LLC-1",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select ship terminal",
        field_options: [
          {
            value: "Motiva Enterprise LLC-1",
          },
          {
            value: "Phillips 66 PL - Pasadena",
          },
          {
            value: "Magellan Pipeline Company L.P-6",
          },
          {
            value: "KM Liquids Terminals LLC",
          },
        ],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "shipped_via",
        field_label: "Shipped Via",
        field_mandatory: "true",
        field_placeholder: "e.g Motiva Enterprise LLC-1",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select shipper",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "autocomplete",
        field_id: "payment_term",
        field_label: "Payment Term",
        field_mandatory: "true",
        field_placeholder: "e.g Net day 1",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select payment term",
        field_options: [
          {
            value: "Net day 1",
          },
          {
            value: "Net day 7",
          },
          {
            value: "Net day 10",
          },
          {
            value: "Net day 15",
          },
        ],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "tax_state",
        field_label: "Tax State",
        field_mandatory: "true",
        field_placeholder: "e.g New York",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select tax state",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "ref",
        field_label: "Ref #",
        field_mandatory: "false",
        field_placeholder: "PO number",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "Please enter PO number",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "invoice_number",
        field_label: "Invoice Number",
        field_mandatory: "true",
        field_placeholder: "Invoice number",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "Please enter invoice number",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "datepicker",
        field_id: "invoice_date",
        field_label: "Invoice Date",
        field_mandatory: "true",
        field_placeholder: "Invoice Date",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select invoice date",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "datepicker",
        field_id: "due_date",
        field_label: "Due Date",
        field_mandatory: "true",
        field_placeholder: "Due Date",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select due date",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "datepicker",
        field_id: "disc_due_date",
        field_label: "Disc Due Date",
        field_mandatory: "false",
        field_placeholder: "Disc Due Date",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select disc due date",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "datepicker",
        field_id: "posting_date",
        field_label: "Posting Date",
        field_mandatory: "true",
        field_placeholder: "Posting Date",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select posting date",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "dropdown",
        field_id: "payment_method",
        field_label: "Payment Method",
        field_mandatory: "true",
        field_placeholder: "Payment Method",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "Please select payment method",
        field_options: [
          {
            value: "cheque",
            title: "Cheque",
          },
          {
            value: "cod",
            title: "COD",
          },
          {
            value: "online",
            title: "Online",
          },
        ],
        field_layout: "vertical",
      },
      {
        field: "toggle",
        field_id: "payment_hold",
        field_label: "Payment on hold",
        field_mandatory: "false",
        field_placeholder: "",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "contract_number",
        field_label: "Contract number",
        field_mandatory: "false",
        field_placeholder: "Contract number",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "Please enter contract number",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "deferred_invoice_number",
        field_label: "Deferred invoice number",
        field_mandatory: "false",
        field_placeholder: "Deferred invoice number",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "Please enter deferred invoice number",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "datepicker",
        field_id: "deferred_tax_due_date",
        field_label: "Deferred tax due date",
        field_mandatory: "false",
        field_placeholder: "Deferred tax due date",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "Please select deferred tax due date",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "checkbox",
        field_id: "copy_bol_datetime",
        field_label: "Copy BOL and datetime ",
        field_mandatory: "false",
        field_placeholder: "",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "autocomplete",
        field_id: "product",
        field_label: "Product",
        field_mandatory: "false",
        field_placeholder: "e.g Product 1",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "",
        field_options: [
          {
            value: "Product 1",
          },
          {
            value: "Product 2",
          },
          {
            value: "Product 3",
          },
          {
            value: "Product 4",
          },
        ],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "bill_of_landing",
        field_label: "Bill of landing",
        field_mandatory: "false",
        field_placeholder: "Bill of landing",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "datepicker",
        field_id: "pickup_date",
        field_label: "Pickup date",
        field_mandatory: "false",
        field_placeholder: "Pickup date",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "gross_quantity",
        field_label: "Gross quantity",
        field_mandatory: "false",
        field_placeholder: "Gross quantity",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "net_quantity",
        field_label: "Net quantity",
        field_mandatory: "false",
        field_placeholder: "Net quantity",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "product_rate",
        field_label: "Rate",
        field_mandatory: "false",
        field_placeholder: "Rate",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "taxes",
        field_label: "Taxes",
        field_mandatory: "false",
        field_disabled: "true",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "def_taxes",
        field_label: "Def taxes",
        field_mandatory: "false",
        field_placeholder: "Total Taxes",
        field_disabled: "true",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "line_total",
        field_label: "Line total",
        field_mandatory: "false",
        field_placeholder: "Line Total",
        field_disabled: "true",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "description",
        field_label: "Description",
        field_mandatory: "false",
        field_placeholder: "Description",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "dropdown",
        field_id: "chart_of_account",
        field_label: "Chart of account",
        field_mandatory: "false",
        field_placeholder: "Search chart of account",
        field_disabled: "false",
        field_type: "text",
        field_value: "",
        field_message: "",
        field_options: [
          {
            value: "payment account",
            title: "Payment Account",
          },
          {
            value: "vendor account",
            title: "Vendor Account",
          },
          {
            value: "sales account",
            title: "Sales Account",
          },
          {
            value: "purchase account",
            title: "Purchase Account",
          },
        ],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "other_quantity",
        field_label: "Quantity",
        field_mandatory: "false",
        field_placeholder: "Quantity",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "other_rate",
        field_label: "Rate",
        field_mandatory: "false",
        field_placeholder: "Rate",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "other_disc",
        field_label: "Disc",
        field_mandatory: "false",
        field_placeholder: "Disc",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "other_taxes",
        field_label: "Taxes",
        field_mandatory: "false",
        field_placeholder: "Taxes",
        field_disabled: "false",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "other_line_total",
        field_label: "Line total",
        field_mandatory: "false",
        field_placeholder: "Line total",
        field_disabled: "true",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "vertical",
      },
      {
        field: "input",
        field_id: "sub_total",
        field_label: "Sub total",
        field_mandatory: "false",
        field_placeholder: "Sub total",
        field_disabled: "true",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "horizontal",
      },
      {
        field: "input",
        field_id: "taxes_total",
        field_label: "Taxes",
        field_mandatory: "false",
        field_placeholder: "Taxes",
        field_disabled: "true",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "horizontal",
      },
      {
        field: "input",
        field_id: "total",
        field_label: "Total",
        field_mandatory: "false",
        field_placeholder: "Total",
        field_disabled: "true",
        field_type: "number",
        field_value: "",
        field_message: "",
        field_options: [],
        field_layout: "horizontal",
      },
    ],
  },
];
